package:
  name: crispressosea
  version: "0.1.3"

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"

requirements:
  host:
    - python >=3.7
    - pip
    - crispresso2
  run:
    - python >=3.7
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - scipy
    - statsmodels
    - jinja2
    - crispresso2

test:
  commands:
    - python -c "import CRISPRessoSea"

about:
  home: "https://github.com/clementlab/CRISPRessoSea"
  summary: "CRISPRessoSea: pooled CRISPR analysis pipeline"
  description: |
    CRISPRessoSea is a tool for analyzing pooled CRISPR sequencing data.

extra:
  recipe-maintainers:
    - kclem
